// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQ91rJvliJ-L4QqTh2Au7EmiOXflT290',
    appId: '1:893751559730:web:9f8f0790d014c90abe1e2b',
    messagingSenderId: '893751559730',
    projectId: 'gnptest-9d471',
    authDomain: 'gnptest-9d471.firebaseapp.com',
    storageBucket: 'gnptest-9d471.appspot.com',
    measurementId: 'G-5DH8H7J07V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGO_EIuKTIN6VAuYl0pLyIKXatMSLZMqY',
    appId: '1:893751559730:android:a6e68bad85d1ef50be1e2b',
    messagingSenderId: '893751559730',
    projectId: 'gnptest-9d471',
    storageBucket: 'gnptest-9d471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSQwQwAQVtH8B66hlzEj7M2QC33b7ZM1M',
    appId: '1:893751559730:ios:6d6949e159c71739be1e2b',
    messagingSenderId: '893751559730',
    projectId: 'gnptest-9d471',
    storageBucket: 'gnptest-9d471.appspot.com',
    iosClientId: '893751559730-4ggp4f96105ukkrg1r5mrcscssgch1oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpnTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSQwQwAQVtH8B66hlzEj7M2QC33b7ZM1M',
    appId: '1:893751559730:ios:4e2e3c0344835f16be1e2b',
    messagingSenderId: '893751559730',
    projectId: 'gnptest-9d471',
    storageBucket: 'gnptest-9d471.appspot.com',
    iosClientId: '893751559730-bvchcg9d7vvtftif15pq1pb872nikavm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpnTest.RunnerTests',
  );
}
